name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-jar
          path: build/libs/*.jar

      - name: Copy JAR to artifacts folder
        run: |
          mkdir -p artifacts
          cp build/libs/*.jar artifacts/

      - name: Commit and push JAR to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN1 }}@github.com/loc-de/apjp-practice-6.git
          git pull origin main
          git add artifacts/*.jar
          git commit -m "Add built JAR [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main